services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - proxynet

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 125829120
      KAFKA_REPLICA_FETCH_MAX_BYTES: 125829120
      KAFKA_FETCH_MAX_BYTES: 125829120
    networks:
      - proxynet

  akhq:
    image: tchiotludo/akhq:latest
    container_name: akhq
    ports:
      - "8082:8080"
    depends_on:
      - kafka
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka:
              properties:
                bootstrap.servers: "kafka:9092"
    networks:
      - proxynet
  
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: aguas_user
      POSTGRES_PASSWORD: aguas_password
      POSTGRES_DB: aguas_db
    ports:
      - "5432:5432"
    networks:
      - proxynet

  srv_ingestion:
    build:
      context: .
    image: srv_ingestion:latest
    container_name: srv_ingestion
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - kafka
    networks:
      - proxynet

networks:
  proxynet:
    name: aguas_network